### ISSUE TITLE
Encoder bank 4 controls send 3, but there are no controls for sends 1 and 2

### ISSUE THREAD

**Issue by CoenKonings** [LukasP46/BCF2000plus#1]
I think it would be more useful to have the encoders control send 1 instead of send 3

**Comment by LukasP46** [comment]
Unfortunately, I no longer use the programme myself, as I now use the Mackie function of the controller. Theoretically, however, it should be easy to change, you are welcome to make a pull request.

**Comment by CoenKonings** [comment]
Thanks for your reply! I'll look into it when I have some time, probably next weekend.

**Comment by CoenKonings** [comment]
I had some spare time today, so I fixed the issue and made a pull request.
